name: Update README

on:
  push:
    paths:
      - 'chains.json'

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update main README
      run: node .github/actions/update_readme.js

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global core.autocrlf true
        git add -A
        git commit -m "Update main README" || echo "No changes to commit"
        git pull --rebase
        git push