name: Update README

on:
  push:
    paths:
      - 'chains.json'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update README
        run: node .github/actions/update_readme.js