name: Update service_ibc_relayer.md files

on:
  push:
    paths:
      - 'relayers.json'

jobs:
  update_service_relayer:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Update service RELAYER
      run: node .github/actions/update_relayer_md.js

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global core.autocrlf true
        git add -A
        git commit -m "Update Relayer service files" || echo "No changes to commit"
        git pull --rebase
        git push
