on: [push, pull_request, workflow_dispatch]
name: Validate JSON schema
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - name: Validate chains.json schema
        uses: walbo/validate-json@v1.1.0
        with:
          files: ./chains.json
          schema: chains.schema.json
          schema-version: draft-07
          fail-on-missing-schema: true